# SmartMeet AI Agent Kubernetes deployment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartmeet-backend
  namespace: smartmeet
  labels:
    app: smartmeet-backend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smartmeet-backend
  template:
    metadata:
      labels:
        app: smartmeet-backend
        version: v1
    spec:
      containers:
      - name: backend
        image: gcr.io/YOUR_PROJECT_ID/smartmeet-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: GOOGLE_CLOUD_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: smartmeet-secrets
              key: google-project-id
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: smartmeet-secrets
              key: google-client-id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: smartmeet-secrets
              key: google-client-secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: smartmeet-secrets
              key: jwt-secret
        - name: WEBHOOK_TOKEN
          valueFrom:
            secretKeyRef:
              name: smartmeet-secrets
              key: webhook-token
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: service-account
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: service-account
        secret:
          secretName: google-service-account
      serviceAccountName: smartmeet-sa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartmeet-frontend
  namespace: smartmeet
  labels:
    app: smartmeet-frontend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smartmeet-frontend
  template:
    metadata:
      labels:
        app: smartmeet-frontend
        version: v1
    spec:
      containers:
      - name: frontend
        image: gcr.io/YOUR_PROJECT_ID/smartmeet-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: smartmeet-backend-service
  namespace: smartmeet
spec:
  selector:
    app: smartmeet-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: smartmeet-frontend-service
  namespace: smartmeet
spec:
  selector:
    app: smartmeet-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartmeet-ingress
  namespace: smartmeet
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "smartmeet-ip"
    networking.gke.io/managed-certificates: "smartmeet-ssl-cert"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: your-domain.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: smartmeet-backend-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smartmeet-frontend-service
            port:
              number: 80

---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: smartmeet-ssl-cert
  namespace: smartmeet
spec:
  domains:
    - your-domain.com

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smartmeet-sa
  namespace: smartmeet
  annotations:
    iam.gke.io/gcp-service-account: smartmeet-agent@YOUR_PROJECT_ID.iam.gserviceaccount.com

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smartmeet-backend-hpa
  namespace: smartmeet
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smartmeet-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80